### ISSUE TITLE
[API Bug] Login API

### ISSUE THREAD

**Issue by dlouistandio** [ALTA-Gurumu/Backend#64]
1.Unregistered user login response code harusnya 400 yang muncul 500
![Image](https://user-images.githubusercontent.com/91419177/217603409-120b6275-6597-4755-a38b-7a2838ac27a2.png)

2.Empty json value response code harusnya 400 muncul 200
![Image](https://user-images.githubusercontent.com/91419177/217603783-ce365ea2-c784-4488-a0f9-7957f51cd27a.png)

3.Response body tidak menggunakan format json. Expectednya: { message: "kesalahan iput dari sisi user"}
![Image](https://user-images.githubusercontent.com/91419177/217603971-b35d8a03-1797-4a0e-a4b8-0c2ababcc833.png)

4.Invalid json key response code harusnya 400 muncul 200
![Image](https://user-images.githubusercontent.com/91419177/217604076-a5ecb1f4-5f01-4424-ab3c-64ff1a215162.png)

**Comment by dlouistandio** [comment]
nomor 4 sama 2 response code nya masih 200 mas

**Comment by herdiladania** [comment]
udah 400 mas,
no 2


![Image](https://user-images.githubusercontent.com/50514500/217748162-a9507983-d7cd-4a9b-8f95-cfc53a71e055.png)

no 4


![Image](https://user-images.githubusercontent.com/50514500/217748406-cc42fadd-e818-4f0f-9db8-984533490929.png)
